### PR TITLE
Add an `api` namespace for easier code invocation, spec def of data structure used

### PR DESCRIPTION
**Pull request by JeremS**
Hello, 

I have been working on a refactoring of Metav. The goal is to make it easier to use Metav directly from clojure code instead of the command line. Personally I want to use it alongside something like [badigeon](https://github.com/EwenG/badigeon), metav taking care of naming & tagging the releases and badigeon reusing this metadata to create jars and deploy to clojars, all in one clojure process.

To do so I have restructured the code so that every operation is found in one namespace `metav.api`. One function to create an execution context `metav.api/make-context` (previously from metav.metadata/invocation-context), and each operation (display, spit, release) takes only the context as parameter. 

All the keys in the context have been namespaced so this context can be passed to other operations of other build tools in a safer manner. 

The cli part now uses this api and I tried to factor as much code as possible between the 3 cli operations. 

I also refactored the tests, trying to test the same cases but with the new api.

In the end it is too big a change to the code base to just merge. Still I wondered if you would consider the approach and would be interested in merging after careful review. I'd be cooler to contribute to this project than just start a fork.

Cheers,

### CODE REVIEW

**Comment by jgrodziski** [comment]
Hi Jeremy,

Wow, that's a great contribution with clean code! I would be glad to add you as a contributor to the project.
I played with badigeon recently and like the approach of cleanly separating things.
I would have more time next week to review the code and merge/release.

Thanks, cheers,

Jérémie.

**Comment by JeremS** [comment]
Hey,

Glad you like it, take your time to review it and don't hesitate to ask any question you may have. 

I am starting to code a little build tool using this version of metav and badigeon. Metav provides an execution context I can then pass from task to task. I am taking inspiration from boot for the task system but use interceptors instead of middleware and I already have a prototype with metav's operations as build tasks in such a system. That's fun!

Again don't hesitate to ask any question you may have, I'd also welcome any opinion as to how to make the release better. There shouldn't be any breaking changes but there are some stuff I do a bit differently.

Cheers,

Jeremy.

**Comment by jgrodziski** [comment]
Hi Jeremy,

I just made a minor refactoring related to naming and namespace hierarchy. All the tests are green.
Tell me if it's ok for you, I can then merge the changes into master and release a new minor version.

Cheers,

Jérémie.

**Comment by JeremS** [comment]
Hey Jérémie,

Everything is good to go on my end. Thanks for the corrections in the docs by the way!

Cheers,

Jeremy.

**Comment by jgrodziski** [comment]
Hi Jeremy,

Concerning the '!' as a suffix indicating a stage change within the `display` function, I do not consider printing on stdout to be a state change. For me: 
- `display` is safe and idempotent (do not change the git state)
- `spit!` is not safe but idempotent (always spit the same data, change the repo only once, all things being equals).
- `release!` is not safe nor idempotent (change git repository state at each invocation).
What do you think?

**Comment by JeremS** [comment]
Hey Jeremy, I have just seen that the metav.api/display! function was missing the "!" at the end after the refactor. I messed up while fetching and checking out your changes wanting to make the correction.

Long story short you could just correct the missing "!" and merge. Or I can try to clean up my mess and push again.

Cheers,

Jeremy.

**Comment by JeremS** [comment]
Ok then my correction is even worse, never mind it! However, the metav.cli/perform! uses display!

Apologies again for the git mishandling.

**Comment by JeremS** [comment]
Hey Jérémie,

I think I have put everything back together, the display function doesn't have the !, you are right the operation doesn't change the git state a user can use it at will without any state changing. The commit  I just pushed has the display function properly named and its use in `metav.cli.display/perform!` is now properly named. 

Thanks for taking the time. 

Jeremy.

**Comment by jgrodziski** [comment]
Ok great :) I'll do a live test asap and will merge in master then.

**Pull request merged**
